### PR TITLE
Added APIDocs for DigitalOcean.

### PR DESCRIPTION
**Pull request by shlokgilda**
Added APIDocs for DigitalOcean.

### CODE REVIEW

**Comment by PratikDhanave** [comment]
can you update pull request ?

**Comment by shlokgilda** [comment]
Done.

**Comment by PratikDhanave** [comment]
Hi can share working examples of aws compute package

**Comment by PratikDhanave** [comment]
After changes made

**Comment by shlokgilda** [comment]
Do you mean actual working codes for individual functions?

**Comment by PratikDhanave** [comment]
may be actual test case running on aws will be useful to make sure it not breaking

**Comment by PratikDhanave** [comment]
more work needed

**Comment by shlokgilda** [comment]
Sure. I will look into it.

**Pull request closed without merging**
