### PR TITLE
Implemented authentication and create node of Ali-cloud. And fixed the way of init provider's config.

### PR DESCRIPTION
**Pull request by OddCN**
Implemented Ali-cloud authentication package and create node function of Elastic Cloud Services.

Here is an example video :    https://youtu.be/0nwiRlgeSIg

### CODE REVIEW

**Comment by PratikDhanave** [comment]
hi  OddCN can you add test in it ?

**Comment by OddCN** [comment]
Yes, of course! @PratikDhanave

**Comment by PratikDhanave** [comment]
Hi @OddCN can you improve pull request as suggested by codacy.

**Comment by OddCN** [comment]
Okay, I'll do it now.

**Comment by OddCN** [comment]
Thanks for test pull request again. There are new issues and I am going to solve it.

**Comment by OddCN** [comment]
I will use Codacy to test my repo before create pull request.

**Comment by OddCN** [comment]
@PratikDhanave Thank you very much for guiding me to improve my code. Now the code seems to have passed the testing of Codacy.

**Comment by PratikDhanave** [comment]
@OddCN please update the repo

**Comment by OddCN** [comment]
@PratikDhanave Sorry about that. I will do it soon.

**Pull request merged**
